FagarSms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('',include('superuser.urls')),    
    path('',include('managers.urls')),
    path('',include('employees.urls')),
    #url(r'api/', include('api.urls')), 
]

api/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import (
    LogoutUserAPIView,
    ProfileAPIView,
    apiOverview,
    riskReportList,
    riskReportDetail,
    riskReportCreate,
    incidentAccidentList,
    incidentAccidentDetail,
    incidentAccidentCreate,
)

app_name = 'api'

urlpatterns = [
    # API ENTRY POINT
    path('', apiOverview, name="api-overview"),
    # API RISK REPORT MODEL RELEATED ACTIONS
    path('report-list/', riskReportList, name="report-list"),
	path('report-detail/<str:pk>/', riskReportDetail, name="report-detail"),
    path('report-create/', riskReportCreate, name="report-create"),
    # API INCIDENT/ACCIDENT MODEL RELEATED ACTIONS
    path('incident-accident-list/', incidentAccidentList, name="incident-accident-list"),
	path('incident-accident-detail/<str:pk>/', incidentAccidentDetail, name="incident-accident-detail"),
    path('incident-accident-create/', incidentAccidentCreate, name="incident-accident-create"),
    # API LOGIN AND AUTH
    url(r'^auth/login/$', obtain_auth_token, name='auth_user_login'),   
    url(r'^auth/logout/$', LogoutUserAPIView.as_view(), name='auth_user_logout'),
    url(r'^profile/$', ProfileAPIView.as_view(), name='user_profile')
]

employees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from .views import (    	
    EmployeeDashboardView,
    
    EmployeeProfileView,
    EmployeeProfileUpdate, #for basic data
    EmployeeProfilePicUpdateView, #for only the profile picture
    EmployeeRiskReportListView, #El empleado solo debe ver los reportes hechos por el mismo
    EmployeeRiskReportListWithSearchView,
    EmployeeRiskReportDetailView,
    EmployeeCreateRiskReportView,
    EmployeeIncidentAccidentListView,
    EmployeeIncidentAccidentListWithSearchView,
    EmployeeIncidentAccidentDetailView,
    EmployeeCreateIncidentAccidentView,
    EmployeeTaskListView,
    EmployeeUpdateTaskStatusView,
)

app_name = 'employees'

urlpatterns = [    
    path('employee/dashboard/', EmployeeDashboardView.as_view(), name='dashboard'),
    path('employee/dashboard/profile/', EmployeeProfileView.as_view(), name='profile'),
    path('employee/dashboard/profile_update/', EmployeeProfileUpdate.as_view(), name='update-profile'),
    path('employee/dashboard/profile_pic_update/', EmployeeProfilePicUpdateView.as_view(), name='update-profile-pic'),
    path('employee/dashboard/risk-report-list/', EmployeeRiskReportListView.as_view(), name='risk-report-list'),
    path('employee/dashboard/risk-report-search/', EmployeeRiskReportListWithSearchView.as_view(), name='risk-report-search'),    
    path('employee/dashboard/risk-report-detial/<int:id>/', EmployeeRiskReportDetailView.as_view(), name='risk-report-detail'),
    path('employee/dashboard/risk-report-create/', EmployeeCreateRiskReportView.as_view(), name='risk-report-create'),    
    path('employee/dashboard/incident-accident-list/', EmployeeIncidentAccidentListView.as_view(), name='incident-accident-list'),
    path('employee/dashboard/incident-accident-search/', EmployeeIncidentAccidentListWithSearchView.as_view(), name='incident-accident-search'),    
    path('employee/dashboard/incident-accident-detial/<int:id>/', EmployeeIncidentAccidentDetailView.as_view(), name='incident-accident-detail'),
    path('employee/dashboard/incident-accident-create/', EmployeeCreateIncidentAccidentView.as_view(), name='incident-accident-create'),
    #task, defenses views
    path('employee/dashboard/task-list/', EmployeeTaskListView.as_view(), name='task-list'),
    path('employee/dashboard/task-status-update/<int:id>/', EmployeeUpdateTaskStatusView.as_view(), name='task-update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, reverse_lazy

from .views import (
    LandingView,
	LoginView,
    LogoutView,        
)

app_name = 'landing'

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('login/', LoginView.as_view(), name='login'),       
    path('logout/', LogoutView.as_view(), name='logout'),   
]

employees/models.py
from django.db import models

# Create your models here.

employees/forms.py
from django import forms
from users.models import SmsManager, RiskReport, Employee, IncidentAccident

class EmployeeProfileFormModal(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['name', 'last_name', 'phone']

class EmployeePicFormModal(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['photo',]


class EmployeeRiskReportForm(forms.ModelForm):

    class Meta:
        model = RiskReport
        fields = ['date', 'place', 'type_of_risk', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description', 'recmendations',]  
        """widgets = {
          'description': forms.Textarea(attrs={'rows':20, 'cols':15}),
        }"""

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(EmployeeRiskReportForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })
        self.fields['recmendations'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

class EmployeeIncidentAccidentForm(forms.ModelForm):

    class Meta:
        model = IncidentAccident
        fields = ['date', 'only_incident','place', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description',]        

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(EmployeeIncidentAccidentForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

employees/views.py
from django.db.models import Count

from datetime import datetime, date

from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse

# email verification and password reset stuff
from django.core.mail import send_mail
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site

from django.views import View
from django.views.generic.base import RedirectView
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    ListView,
    DeleteView,
    FormView
)

from users.models import User, SmsManager, RiskReport, Employee, Company, IncidentAccident, Task
from .forms import EmployeeProfileFormModal, EmployeePicFormModal, EmployeeRiskReportForm, EmployeeIncidentAccidentForm

class EmployeeDashboardView(View):
    template_name = "employee/employeeStart.html"     

    def get(self, request, *args, **kwargs):
        # GET method
        context={}
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)
        context["employee"] = employee
        company = get_object_or_404(Company, employee_of_company=employee)
        context["company"] = company
        context["totalRiskReports"] = RiskReport.objects.filter(owner=employee.user).count()
        context["totalIncidentes"] = IncidentAccident.objects.filter(owner=employee.user).count()
        context["uncompleted"]  = Task.objects.filter(reponsable=employee.user, completedTask=False).count()
        return render(request, self.template_name, context)    
        
class EmployeeProfileView(DetailView):
    model           = Employee
    template_name   = 'employee/employeeProfile.html'    

    def get_object(self):        
        id_ = self.request.user.id
        return get_object_or_404(Employee, user=id_)

class EmployeeProfileUpdate(UpdateView):
    model = Employee
    template_name = 'employee/modals/employeeUpdateProfile.html'
    form_class = EmployeeProfileFormModal

    def get_object(self):        
        id_ = self.request.user.id
        return get_object_or_404(Employee, user=id_)    

    def get_success_url(self):
            return reverse('employees:profile')

class EmployeeProfilePicUpdateView(UpdateView):
    model           = Employee
    template_name   = 'employee/modals/employeeUpdateProfilePic.html'
    form_class      = EmployeePicFormModal

    def get_object(self):        
        id_ = self.request.user.id
        return get_object_or_404(Employee, user=id_)    

    def get_success_url(self):
        return reverse('employees:profile')

#RISK REPORTS VIEWS
class EmployeeRiskReportListView(ListView):
    model = RiskReport    
    paginate_by = 10
    context_object_name = 'risk_reports'
    template_name = 'employee/riskReports/employeeRiskReportList.html'

    def get_context_data(self, **kwargs):
        #obtengo id del empleado
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)        
        kwargs['employee'] = employee
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        #obtengo id del empleado
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)
        #obtengo solo los reportes hechos por este empleado
        queryset = RiskReport.objects.filter(owner=employee.user).order_by('-id')
        return queryset

class EmployeeRiskReportListWithSearchView(ListView):
    model = RiskReport    
    paginate_by = 10
    context_object_name = 'risk_reports'
    template_name = 'employee/riskReports/employeeRiskReportList.html'

    def get_queryset(self):
        id_             = self.request.user.id
        employee        = get_object_or_404(Employee, user=id_)        
        company         = employee.company        
        my_search       = self.request.GET.get('my_search')        
        new_queryset    = RiskReport.objects.filter(owner=employee.user, of_company=company, description__unaccent__icontains=my_search).order_by('-id')
        return new_queryset

    def get_context_data(self, **kwargs):
        context                 = super(EmployeeRiskReportListWithSearchView, self).get_context_data(**kwargs)
        context['my_search']    = self.request.GET.get('my_search')
        return context

class EmployeeRiskReportDetailView(DetailView):
    template_name = 'employee/riskReports/employeeRiskReportDetail.html'
    model         = RiskReport   

    def get_object(self):        
        id_ = self.kwargs.get("id")        
        return get_object_or_404(RiskReport, id=id_)

class EmployeeCreateRiskReportView(CreateView):
    model = RiskReport    
    template_name = 'employee/riskReports/employeeRiskReportCreate.html'
    form_class      = EmployeeRiskReportForm    

    def form_valid(self, form):        
        new_report = form.save(commit=False)
        new_report.owner = self.request.user
        #obtengo id del empleado
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)            
        new_report.of_company = employee.company        
        # save report
        new_report.save()
        # email notification to manager
        # company         = employee.company
        # manager         = company.company_sms_manager        
        # domain          = get_current_site(self.request).domain
        # link            = reverse('managers:risk-report-detail', kwargs={'id':new_report.id})
        # report_url      = 'http://'+domain+link        
        # email_subject   = '[Fagar-SMS] '+employee.name+' '+employee.last_name+' ha creado un reporte de riesgo para '+company.name
        # emai_body       = employee.name+' '+employee.last_name+' ha creado un reporte de riesgo\n'+'Puedes revisarlo en el siguiente link: '+report_url        
        # send_mail(
        #     email_subject, 
        #     emai_body,
        #     #'noreply@fagar.com'
        #     'fg.sos.store@gmail.com',
        #     #['manager.user'], #recipients list
        #     ['fg.sos.store@gmail.com'],
        #     fail_silently=False,
        # )    
        return redirect('employees:risk-report-list')

###################################INCIDENTS-ACCIDENTS REPORTS VIEWS
class EmployeeIncidentAccidentListView(ListView):
    model = IncidentAccident    
    paginate_by = 10
    context_object_name = 'incidents_accidents'
    template_name = 'employee/incidents_and_accidents/employeeIncidentAccidentList.html'

    def get_context_data(self, **kwargs):
        #obtengo id del empleado y el empleado asociado
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)        
        kwargs['employee']          = employee
        company                     = employee.company
        kwargs['incidents']         = IncidentAccident.objects.filter(of_company=company, only_incident='1').order_by('-id')
        kwargs['accidents']         = IncidentAccident.objects.filter(of_company=company, only_incident='2').order_by('-id')
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        #obtengo id del empleado
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)
        #obtengo solo los reportes hechos por este empleado
        queryset = IncidentAccident.objects.filter(owner=employee.user).order_by('-id')
        return queryset

class EmployeeIncidentAccidentListWithSearchView(ListView):
    model               = IncidentAccident    
    paginate_by         = 10
    context_object_name = 'incidents_accidents'
    template_name = 'employee/incidents_and_accidents/employeeIncidentAccidentList.html'

    def get_context_data(self, **kwargs):
        context                 = super(EmployeeIncidentAccidentListWithSearchView, self).get_context_data(**kwargs)
        context['my_search']    = self.request.GET.get('my_search')        
        my_search               = self.request.GET.get('my_search')
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)        
        kwargs['employee']      = employee
        company                 = employee.company        
        incidents               = IncidentAccident.objects.filter(of_company=company, only_incident='1', description__unaccent__icontains=my_search).order_by('-id')
        accidents               = IncidentAccident.objects.filter(of_company=company, only_incident='2', description__unaccent__icontains=my_search).order_by('-id')        
        kwargs['incidents']     = incidents
        kwargs['accidents']     = accidents
        return super().get_context_data(**kwargs)

class EmployeeIncidentAccidentDetailView(DetailView):
    template_name = 'employee/incidents_and_accidents/employeeIncidentAccidentDetail.html'
    model         = IncidentAccident   

    def get_object(self):        
        id_ = self.kwargs.get("id")                
        return get_object_or_404(IncidentAccident, id=id_)

class EmployeeCreateIncidentAccidentView(CreateView):
    model = IncidentAccident    
    template_name = 'employee/incidents_and_accidents/employeeIncidentAccidentCreate.html'
    form_class      = EmployeeIncidentAccidentForm    

    def form_valid(self, form):        
        new_report = form.save(commit=False)
        new_report.owner = self.request.user
        #obtengo id del empleado
        id_ = self.request.user.id
        employee = get_object_or_404(Employee, user=id_)            
        new_report.of_company = employee.company        
        #guardo el reporte
        new_report.save()
        # email notification to manager
        # company         = employee.company
        # manager         = company.company_sms_manager

employees/templates/employee/employeeDashboard.html
{% extends 'dashboardBase.html' %}
{% load static %}
{% block content %}

{% include './navMobile.html' %}  

<div class="row mb-0">
    <!--Left side panel-->
    {% include './leftSidePanel.html' %}  
       

    <!--Right side panel-->
    <div class="col s12 m9 pl-0 pr-0 main-content">
        {% block dashboard %}

        {% endblock %}
    </div>
</div>

{% endblock %}

employees/templates/employee/employeeProfile.html
{% extends './employeeDashboard.html' %}
{% load static %}
{% block dashboard %}

<div class="row profile-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Perfil</h3>
        </div>       
    </div>
</div>

<!--EMPLOYEE BASIC DATA-->
<div class="row">
    <div class="container">
        <div class="valign-wrapper">
            <div class="row" style="width: 100%;">        
                <div class="col s12">
                    <div class="row text-center">
                        <h4>Información Basica</h4>
                    </div>    
                    <div class="card horizontal">                        
                        <div class="card-image">
                            <img src="{{ object.photo.url }}" class="profile-pic-medium mt-1 mb-1">                            
                            <button data-target="ProfilePicFormModal" class="btn-edit-profile-pic btn-small btn-floating waves-effect waves-light grey darken-2 modal-trigger"><i class="material-icons">add_a_photo</i></button>
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3>{{ object.name }} {{ object.last_name }}</h3>
                                <div class="divider"></div>
                                <br>
                                <p>{{ object.user.email }}</p>
                                <p>{{ object.phone }}</p>                                
                            </div>                
                        </div>
                        <a class="btn-large btn-floating halfway-fab waves-effect waves-light green btn modal-trigger" href="#ProfileFormModal"><i class="material-icons">edit</i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Formulario datos basicos -->
<div id="ProfileFormModal" class="modal">
    <div class="modal-content" id="update-profile-url">
        {% include './modals/employeeUpdateProfile.html' %}
    </div>
</div>
<!-- Modal Formulario foto de perfil -->
<div id="ProfilePicFormModal" class="modal">
    <div class="modal-content" id="update-profile-pic-url">
        {% include './modals/employeeUpdateProfilePicture.html' %}
    </div>
</div>
<!--SCRIPTS-->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript">        
    $( document ).ready(function() {        
        $('.modal').modal();        
        $('#update-profile-url').load("{% url 'employees:update-profile' %}");             
        $('#update-profile-pic-url').load("{% url 'employees:update-profile-pic' %}");
    });
</script>

{% endblock%}

employees/templates/employee/employeeStart.html
{% extends './employeeDashboard.html' %}
{% load static %}
{% block dashboard %}

<div class="col m1 hide-on-med-and-down">

</div>

<div class="col s12 m10 center-by-margin">
    <!--company info -->
    <div class="col s12 m4">
        <div class="card indicator-card horizontal grey lighten-5 z-depth-1 valign-wrapper">                        
            <div class="card-image">
                <img src="{{ company.company_logo.url }}" class="profile-pic-small mt-1 mb-1 ml-1">                        
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <p>{{ company.name }}</p>
                </div>
            </div>
        </div>
    </div>
    <!--employee info -->
    <div class="col s12 m4">
        <div class="card indicator-card horizontal grey lighten-5 z-depth-1 valign-wrapper">                        
            <div class="card-image">
                <img src="{{ employee.photo.url }}" class="profile-pic-small mt-1 mb-1 ml-1">                        
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <p>{{ employee.name }} {{ employee.last_name }}</p>
                </div>
            </div>
        </div>
    </div>
    <!--reports info-->
    <div class="col s12 m4">
        <div class="card indicator-card horizontal grey lighten-5 z-depth-1 valign-wrapper">                                    
            <div class="card-stacked">
                <div class="card-content">
                    <h6>Total de reportes</h6>
                    <p>reportes de riesgo: {{ totalRiskReports }}</p>
                    <p>reportes de incidentes: {{ totalIncidentes }}</p>
                    <p>Tareas pendientes: {{ uncompleted }} </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col m1 hide-on-med-and-down">

</div>

<script>/*
    document.addEventListener('DOMContentLoaded', function () {
        activeLi = document.querySelector('li#item-dashboard').classList.add('active');;
        activeLiIcon = document.querySelector('li#item-dashboard a i').style.color = "#26a69a !important;";
        activeLiIcon = document.querySelector('li#item-dashboard a i').style.backgroundColor = "#fff !important;"
        console.log(activeLiIcon);
    });*/
</script>

{% endblock %}

employees/templates/employee/leftSidePanel.html
<div class="col m3 left-side pl-0 pr-0 menu-container">
    <div class="green-material-square">          
      <div class="menu-logo"></div>
    </div>
    <div>
      <ul class="collection principal-menu mt-0 mb-0">
        <li id="item-dashboard" class="collection-item avatar principal-menu-item">
          <a href="{% url 'employees:dashboard' %}">
            <i class="material-icons circle ">dashboard</i>
            Inicio
          </a>
        </li>          
        <li id="item-profile" class="collection-item avatar principal-menu-item">
          <a href="{% url 'employees:profile' %}">
            <i class="material-icons circle ">person</i>
            Perfil
          </a>
        </li>
        <li id="item-tasks" class="collection-item avatar principal-menu-item">
          <a href="{% url 'employees:task-list' %}" class="pl-0">
            <i class="material-icons circle ">assignment</i>
            Tareas
          </a>
        </li>          
        <li id="item-reports" class="collection-item avatar principal-menu-item">
          <a href="{% url 'employees:risk-report-list' %}">
            <i class="material-icons circle ">report_problem</i>
            Reportes de Riesgo
          </a>
        </li>
        <li id="item-incidents-accidents" class="collection-item avatar principal-menu-item">
          <a href="{% url 'employees:incident-accident-list' %}">
            <i class="material-icons circle ">report</i>
            Incidentes y Accidentes
          </a>
        </li>
        <li id="item-logout" class="collection-item avatar principal-menu-item">
          <a href="{% url 'landing:logout' %}">
            <i class="material-icons circle ">exit_to_app</i>
            Salir
          </a>
      </li>                      
      </ul>
    </div>        
</div> 

employees/templates/employee/navMobile.html
<nav class="nav-mobile">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo right">Fagar-SMS</a>
      <ul class="left">        
        <li><a href="#" data-target="slide-out" class="sidenav-trigger" style="color: #5a5a5a"> <i class="material-icons">menu</i></a></li>        
      </ul>
    </div>
</nav>

<!--Left side panel on mobile-->
<ul id="slide-out" class="sidenav menu-container">
    <li>
        <div class="green-material-square">
          <div class="menu-logo"></div>
        </div>
    </li>
    <li>
        <div>
          <ul class="collection principal-menu mt-0">
            <li class="collection-item avatar principal-menu-item pl-0">
              <a href="{% url 'employees:dashboard' %}" class="pl-0 pr-0">
                <i class="material-icons circle blue">dashboard</i>
                Inicio
              </a>
            </li>          
            <li class="collection-item avatar principal-menu-item pl-0">
              <a href="{% url 'employees:profile' %}" class="pl-0 pr-0">
                <i class="material-icons circle blue">person</i>
                Perfil
              </a>
            </li> 
            <li class="collection-item avatar principal-menu-item pl-0">
              <a href="{% url 'employees:task-list' %}" class="pl-0 pr-0">
                <i class="material-icons circle green">assignment</i>
                Tareas
              </a>
            </li>         
            <li class="collection-item avatar principal-menu-item pl-0">
              <a href="{% url 'employees:risk-report-list' %}" class="pl-0 pr-0">
                <i class="material-icons circle orange">report_problem</i>
                Reportes de Riesgo
              </a>
            </li>
            <li class="collection-item avatar principal-menu-item pl-0">
              <a href="{% url 'employees:incident-accident-list' %}" class="pl-0 pr-0">
                <i class="material-icons circle red">report</i>
                Incidentes y Accidentes
              </a>
            </li>
            <li class="collection-item avatar principal-menu-item pl-0">
              <a href="{% url 'landing:logout' %}" class="pl-0 pr-0">
                <i class="material-icons circle red">exit_to_app</i>
                Salir
              </a>
            </li>                      
          </ul>
        </div>        
    </li>
  </ul>