FagarSms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('',include('superuser.urls')),    
    path('',include('managers.urls')),
    path('',include('employees.urls')),
    #url(r'api/', include('api.urls')), 
]

api/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import (
    LogoutUserAPIView,
    ProfileAPIView,
    apiOverview,
    riskReportList,
    riskReportDetail,
    riskReportCreate,
    incidentAccidentList,
    incidentAccidentDetail,
    incidentAccidentCreate,
)

app_name = 'api'

urlpatterns = [
    # API ENTRY POINT
    path('', apiOverview, name="api-overview"),
    # API RISK REPORT MODEL RELEATED ACTIONS
    path('report-list/', riskReportList, name="report-list"),
	path('report-detail/<str:pk>/', riskReportDetail, name="report-detail"),
    path('report-create/', riskReportCreate, name="report-create"),
    # API INCIDENT/ACCIDENT MODEL RELEATED ACTIONS
    path('incident-accident-list/', incidentAccidentList, name="incident-accident-list"),
	path('incident-accident-detail/<str:pk>/', incidentAccidentDetail, name="incident-accident-detail"),
    path('incident-accident-create/', incidentAccidentCreate, name="incident-accident-create"),
    # API LOGIN AND AUTH
    url(r'^auth/login/$', obtain_auth_token, name='auth_user_login'),   
    url(r'^auth/logout/$', LogoutUserAPIView.as_view(), name='auth_user_logout'),
    url(r'^profile/$', ProfileAPIView.as_view(), name='user_profile')
]

managers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from .views import (    	
    SmsManagerDashboardView,
    SmsManagerProfileView,
    SmsManagerProfileUpdate,
    SmsManagerProfilePicUpdateView,
    SmsManagerRiskReportListView,
    SmsManagerRiskReportListWithSearchView,
    SmsManagerRiskReportDetailView,
    SmsManagerCloseReportView,
    SmsManagerUpdateLevelView,
    SmsManagerUpdateTaskView,
    SmsManagerCreateRiskReportView,
    SmsManagerIncidentAccidentListView,
    SmsManagerIncidentAccidentListWithSearchView,
    SmsManagerIncidentAccidentDetailView,
    SmsManagerCreateIncidentAccidentView,
    SmsManagerEmployeeListView,
    SmsManagerEmployeeListWithSearchView,
    SmsManagerDetailEmployeeView,
    SmsManagerCreateEmployeeView, 
    SmsManagerDeleteEmployeeView, 
    SmsManagerEmployeeProfileUpdate,
    SmsManagerEmployeeProfilePicUpdateView,  
)

from .taskViews import (
    SmsManagerTaskListView,   
    SmsManagerUpdateTaskStatusView,
)

app_name = 'managers'

urlpatterns = [    
    path('sms-manager/dashboard/', SmsManagerDashboardView.as_view(), name='dashboard'),
    path('sms-manager/dashboard/profile/', SmsManagerProfileView.as_view(), name='profile'),
    path('sms-manager/dashboard/profile-update/', SmsManagerProfileUpdate.as_view(), name='update-profile'),
    path('sms-manager/dashboard/profile-pic_update/', SmsManagerProfilePicUpdateView.as_view(), name='update-profile-pic'),    
    # RISK REPORTS
    path('sms-manager/dashboard/risk-report-list/', SmsManagerRiskReportListView.as_view(), name='risk-report-list'),
    path('sms-manager/dashboard/risk-report-search/', SmsManagerRiskReportListWithSearchView.as_view(), name='risk-report-search'),
    path('sms-manager/dashboard/risk-report-detail/<int:id>/', SmsManagerRiskReportDetailView.as_view(), name='risk-report-detail'),
    path('sms-manager/dashboard/risk-report-close/<int:id>/', SmsManagerCloseReportView.as_view(), name='risk-report-close'),
    # LEVEL AND TASK FOR RISK REPORTE
    path('sms-manager/dashboard/risk-report-level-update/<int:id>/', SmsManagerUpdateLevelView.as_view(), name='risk-report-level'),
    path('sms-manager/dashboard/risk-report-task-update/<int:id>/', SmsManagerUpdateTaskView.as_view(), name='risk-report-task'),    
    path('sms-manager/dashboard/risk-report-create/', SmsManagerCreateRiskReportView.as_view(), name='risk-report-create'),
    # INCIDENTS ACCIDENTS
    path('sms-manager/dashboard/incident-accident-list/', SmsManagerIncidentAccidentListView.as_view(), name='incident-accident-list'),
    path('sms-manager/dashboard/incident-accident-search/', SmsManagerIncidentAccidentListWithSearchView.as_view(), name='incident-accident-search'),
    path('sms-manager/dashboard/incident-accident-detial/<int:id>/', SmsManagerIncidentAccidentDetailView.as_view(), name='incident-accident-detail'),
    path('sms-manager/dashboard/incident-accident-create/', SmsManagerCreateIncidentAccidentView.as_view(), name='incident-accident-create'),
    # EMPLOYEES
    path('sms-manager/dashboard/employees-list/', SmsManagerEmployeeListView.as_view(), name='employee-list'),
    path('sms-manager/dashboard/employees-search/', SmsManagerEmployeeListWithSearchView.as_view(), name='employee-search'),    
    path('sms-manager/dashboard/employee-detail/<int:id>/', SmsManagerDetailEmployeeView.as_view(), name='employee-detail'),
    path('sms-manager/dashboard/employee-create/', SmsManagerCreateEmployeeView.as_view(), name='employee-create'),
    path('sms-manager/dashboard/employee-delete/<int:id>/', SmsManagerDeleteEmployeeView.as_view(), name='employee-delete'),    
    path('sms-manager/dashboard/employee-profile-update/<int:id>/', SmsManagerEmployeeProfileUpdate.as_view(), name='employee-update-profile'),
    path('sms-manager/dashboard/employee-profile-pic_update/<int:id>/', SmsManagerEmployeeProfilePicUpdateView.as_view(), name='employee-update-profile-pic'),
    #task, defenses views
    path('sms-manager/dashboard/task-list/', SmsManagerTaskListView.as_view(), name='task-list'),
    path('sms-manager/dashboard/task-status-update/<int:id>/', SmsManagerUpdateTaskStatusView.as_view(), name='task-update'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managers/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.db.models.signals import post_save

from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

from django.utils.translation import ugettext_lazy as _

from django.dispatch import receiver

#USERMANAGER esto para usar el correo electronico como identificador de usuario
class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)        
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

#Clase basica para tener varios tipos de usuarios
class User(AbstractBaseUser, PermissionsMixin):
    email           = models.EmailField(unique=True, blank=False)
    #flags que determinan el rol del usuario
    is_sms_manager	= models.BooleanField(default=False)
    is_employee	= models.BooleanField(default=False)
    #flag staff
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_('Do you think you can be a Superuser?'),
    )
    #flag staff
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    #falg activo
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )    
    
    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

#Clase para los gerentes SMS
class SmsManager(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    #ci          = models.IntegerField(unique=True)
    career      = models.CharField(max_length=50, default='')     
    phone       = models.PositiveBigIntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='sms_managers/profile_pics/', default='sms_managers/profile_pics/default_user_profile_pic.png')    

TYPE_OF_COMPANY = (
    ('1', 'Airport'),#Aeropuerto
    ('2', 'Aeroline'),#Personas Juridicas
    ('3', 'ciac'),#centro de instrucción
    ('4', 'omac'),#Taller OMAC    
)

class Company(models.Model):
    #todo compañia debe tener un gerente sms
    #tambien muchas compañias pueden tener un mismo gerete sms
    company_sms_manager = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='managed_by')
    name                = models.CharField(max_length=100)
    type_of_company     = models.CharField(max_length=1, choices=TYPE_OF_COMPANY, blank=True)
    #rav_type           = models.CharField(max_length=1, choices=TYPE_OF_RAP, blank=True)
    #una compañia puede tener mas de rav
    #hay regulaciones por otros paises rap (peru), far(estados unidos), etc
    #rav_number         = models.IntegerField(null=False, default=0)
    phone               = models.PositiveBigIntegerField(null=False, default=0)
    company_logo        = models.ImageField(upload_to='companys/company_logos/', default='companys/company_logos/default_company_logo.png')
    rif                 = models.PositiveBigIntegerField(null=False, default=0)
    company_mail        = models.EmailField(blank=False, default='mail@mail.com')

class Employee(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    #muchos empleados pertenecen a una compañia
    company     = models.ForeignKey(Company, on_delete=models.CASCADE, related_name = 'employee_of_company', default = False)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    phone       = models.PositiveBigIntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='employees/profile_pics/', default='employees/profile_pics/default_user_profile_pic.png')    

TYPE_OF_RISK = (
    ('1', 'Relacionado con vuelo'),
    ('2', 'E.P.P. (Equipos de protección personal)'),
    ('3', 'Procedimientos'),
    ('4', 'Mantenimiento Aeronáutico'),
    ('5', 'FOD (Objetos extraños)'),
    ('6', 'Orden y limpieza'),
    ('7', 'Acto inseguro'),
    ('8', 'Otros'),
)

LEVEL_OF_RISK = (
    ('1', 'Aceptable'),
    ('2', 'Moderado'),
    ('3', 'Alto'),
    ('4', 'Extremo')    
)

PROBABILITY = (
    ('1', 'Improbable'),
    ('2', 'Remoto'),
    ('3', 'Ocasional'),    
    ('4', 'Frecuente'),
    ('5', 'Probable'),
)

CONSEQUENCE = (
    ('1', 'Insignificante'),
    ('2', 'Menor'),
    ('3', 'Moderado'),    
    ('4', 'Grave'),
    ('5', 'Catastrofico'), 
)


class RiskReport(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='reports_of_company')
    create_at_date  = models.DateTimeField(auto_now_add=True)    
    date            = models.DateField()
    place           = models.CharField(max_length=100)
    type_of_risk    = models.CharField(max_length=1, choices=TYPE_OF_RISK, blank=True)
    photo1          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo2          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo3          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo4          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo5          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    description     = models.TextField(blank=True)
    recmendations   = models.TextField(blank=True, default='')
    is_open         = models.BooleanField(default=True)
    level_of_risk   = models.CharField(max_length=1, choices=LEVEL_OF_RISK, blank=True)
    probability     = models.CharField(max_length=1, choices=PROBABILITY, blank=True)
    consequence     = models.CharField(max_length=1, choices=PROBABILITY, blank=True)            
    level           = models.IntegerField(null=False, default=0)
     
INCIDENT_OR_ACCIDENT = (
    ('1', 'Incidente'),
    ('2', 'Accidente'),
)

class IncidentAccident(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='incident_accident_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='incident_accident_of_company')
    create_at_date  = models.DateTimeField(auto_now_add=True)
    only_incident   = models.CharField(max_length=1, choices=INCIDENT_OR_ACCIDENT, default='1')
    date            = models.DateField()
    place           = models.CharField(max_length=100)    
    photo1          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo2          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo3          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo4          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo5          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    description     = models.TextField(blank=True)

class Task(models.Model):    
    assigned_date   = models.DateTimeField(auto_now_add=True)    
    report          = models.ForeignKey(RiskReport, on_delete=models.CASCADE, related_name='task_of_report')
    reponsable      = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task_of_user')
    manager         = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='task_of_manager', null=True)
    employee        = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='task_of_employee', null=True)
    taskDescription = models.TextField(blank=False)
    completedTask   = models.BooleanField(default=False)
    completed_date  = models.DateTimeField(blank=True, null=True)    

managers/templates/managers/modals/employeeDelete.html
{% load static %}
<h4>¿Seguro que desea eliminar este empleado?</h4>

<form id="deleteEmployeeForm" style="text-align: center;" action="" method="post">    
    {% csrf_token %}  
    <inpunt id="toView" type="hidden"></inpunt>  
        <button type='submit' class="waves-effect waves-light btn-large white-text">
            Si&nbsp;
        </button>
        <a class="waves-effect waves-light btn-large modal-close">No</a>
</form>

managers/templates/managers/modals/employeeUpdateProfile.html
{% load static %}
<form action="{% url 'managers:employee-update-profile' object.user.id %}" method="post">
    {% csrf_token %}        
    <div class="row">
        <div class="input-field col s12">    
            {{ form.name }}
            <label for="id_name">Nombre:</label>
        </div>
    </div>
                    
    <div class="row">
        <div class="input-field col s12">
            {{ form.last_name }}
            <label for="id_last_name">Apellido:</label>
        </div>
    </div>
            
    <div class="row">
        <div class="input-field col s12">
            {{ form.phone }}
            <label for="id_phone">Telefono:</label>
        </div>
    </div>
    <button type='submit' class="waves-effect waves-light btn-large white-text">
        Guardar
    </button>
</form>
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
<script type="text/javascript">        
        M.updateTextFields();
</script>

managers/templates/managers/modals/employeeUpdateProfilePicture.html
<form action="{% url 'managers:employee-update-profile-pic' object.user.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}        
    <div class="file-field input-field">
        <div class="btn">
            <span>Seleccionar Foto de Perfil</span>
            <input type="file" name="photo" accept="image/*" id="id_photo">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
        </div>
    </div>
    <button type='submit' class="waves-effect waves-light btn-large white-text">
        Subir Foto
    </button>
</form>

managers/templates/managers/modals/managerUpdateProfile.html
{% load static %}
<form action="{% url 'managers:update-profile' %}" method="post">
    {% csrf_token %}        
    <div class="row">
        <div class="input-field col s12">    
            {{ form.name }}
            <label for="id_name">Nombre:</label>
        </div>
    </div>
                    
    <div class="row">
        <div class="input-field col s12">
            {{ form.last_name }}
            <label for="id_last_name">Apellido:</label>
        </div>
    </div>
            
    <div class="row">
        <div class="input-field col s12">
            {{ form.phone }}
            <label for="id_phone">Telefono:</label>
        </div>
    </div>
    <button type='submit' class="waves-effect waves-light btn-large white-text">
        Guardar
    </button>
</form>
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
<script type="text/javascript">        
        M.updateTextFields();
</script>

managers/templates/managers/modals/managerUpdateProfilePicture.html
<form action="{% url 'managers:update-profile-pic' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}        
    <div class="file-field input-field">
        <div class="btn">
            <span>Seleccionar Foto de Perfil</span>
            <input type="file" name="photo" accept="image/*" id="id_photo">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
        </div>
    </div>
    <button type='submit' class="waves-effect waves-light btn-large white-text">
        Subir Foto
    </button>
  </form>

managers/templates/managers/modals/riskReportAddLevel.html
{% load static %}
<h3>Establezca el nivel de riesgo</h3>
<form action="{% url 'managers:risk-report-level' object.id %}" method="post" enctype="multipart/form-data" class="col s12 center-by-margin" style="overflow: visible;">
    {% csrf_token %}
    
    <div class="row mt-1">
        <select name="probability" id="id_probability">
            <option value="" disabled selected>Seleccióne el nivel de probabilidad</option>
            <option value="1" data-icon="{% static '/Images/riskColors/1-improbable-insignificante.png'%}">Improbable</option>
            <option value="2" data-icon="{% static '/Images/riskColors/2-remoto-menor.png'%}">Remoto</option>
            <option value="3" data-icon="{% static '/Images/riskColors/3-ocasional-modarado.png'%}">Ocasional</option>
            <option value="4" data-icon="{% static '/Images/riskColors/4-frecuente-grave.png'%}">Frecuente</option>
            <option value="5" data-icon="{% static '/Images/riskColors/5-probable-catastrofico.png'%}">Muy probable</option>
        </select>                        
    </div>
    
    <div class="row mt-1">
        <select name="consequence" id="id_consequence">
            <option value="" disabled selected>Seleccione el nivel de severidad</option>
            <option value="1" data-icon="{% static '/Images/riskColors/1-improbable-insignificante.png'%}">Insignificante</option>
            <option value="2" data-icon="{% static '/Images/riskColors/2-remoto-menor.png'%}">Menor</option>
            <option value="3" data-icon="{% static '/Images/riskColors/3-ocasional-modarado.png'%}">Moderado</option>
            <option value="4" data-icon="{% static '/Images/riskColors/4-frecuente-grave.png'%}">Grave</option>
            <option value="5" data-icon="{% static '/Images/riskColors/5-probable-catastrofico.png'%}">Catastrofico</option>
        </select>                        
    </div> 
    
    <div class="row center">                                
        <button type='submit' class="waves-effect waves-light btn-large white-text">
            Guardar
        </button>
    </div>
    </div>    
</form>

managers/templates/managers/modals/riskReportAddTask.html
{% load static %}
<h4>Añadir una nueva defensa</h4>
<form method="post" action="/sms-manager/dashboard/risk-report-task-update/{{ report.id }}/" class="col s12 center-by-margin">
    {% csrf_token %}
    
    <div class="row">
        <div class="input-field col s12">
            <select name="reponsable" required id="id_reponsable">
                {% if form.reponsable.value == None %}
                    <option value="" disabled selected>Debe seleccionar un responsable</option>                           
                {% endif %}                
                    <option value="{{ manager.user.id }}" data-icon="{{ manager.photo.url }}">{{ manager.user }}</option>
                {% for employee in employees %}
                    <option value="{{ employee.user.id }}" data-icon="{{ employee.photo.url }}">{{ employee.user }}</option>        
                {% endfor %}
            </select>
            <label for="id_reponsable">Responsable:</label>
        </div>
    </div>
    
    <div class="row">
        <div class="input-field col s12">    
            {{ form.taskDescription }}
            <label for="id_taskDescription">Descripción:</label>
        </div>
    </div>
    
    <div class="row center">                                
        <button type='submit' class="waves-effect waves-light btn-large white-text">
            Guardar
        </button>
    </div>    
</form>

<script>
    $(document).ready(function(){
        $('.modal').modal();
        $('select').formSelect();
    });
  </script>

managers/templates/managers/modals/riskReportclose.html
{% load static %}
<h4>¿Seguro que desea cerrar este reporte de riesgo?</h4>

<form id="closeReportForm" style="text-align: center;" action="" method="post">    
    {% csrf_token %}  
    <inpunt id="toView" type="hidden"></inpunt>  
        <button type='submit' class="waves-effect waves-light btn-large white-text">
            Si&nbsp;
        </button>
        <button class="modal-close waves-effect waves-light btn-large white-text">
            No
        </button>
</form>

managers/templates/managers/modals/taskUpdateStatus.html
{% load static %}
<h4>¿Seguro que desea cambiar el estado de la tarea?</h4>

<form id="updateTaskStatusForm" style="text-align: center;" action="" method="post">    
    {% csrf_token %}
        <inpunt id="toView" type="hidden"></inpunt>
        <button type='submit' class="waves-effect waves-light btn-large white-text">
            Si
        </button>        
        <a class="waves-effect waves-light btn-large modal-close">No</a>
</form>