FagarSms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('',include('superuser.urls')),    
    path('',include('managers.urls')),
    path('',include('employees.urls')),
    #url(r'api/', include('api.urls')), 
]

api/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import (
    LogoutUserAPIView,
    ProfileAPIView,
    apiOverview,
    riskReportList,
    riskReportDetail,
    riskReportCreate,
    incidentAccidentList,
    incidentAccidentDetail,
    incidentAccidentCreate,
)

app_name = 'api'

urlpatterns = [
    # API ENTRY POINT
    path('', apiOverview, name="api-overview"),
    # API RISK REPORT MODEL RELEATED ACTIONS
    path('report-list/', riskReportList, name="report-list"),
	path('report-detail/<str:pk>/', riskReportDetail, name="report-detail"),
    path('report-create/', riskReportCreate, name="report-create"),
    # API INCIDENT/ACCIDENT MODEL RELEATED ACTIONS
    path('incident-accident-list/', incidentAccidentList, name="incident-accident-list"),
	path('incident-accident-detail/<str:pk>/', incidentAccidentDetail, name="incident-accident-detail"),
    path('incident-accident-create/', incidentAccidentCreate, name="incident-accident-create"),
    # API LOGIN AND AUTH
    url(r'^auth/login/$', obtain_auth_token, name='auth_user_login'),   
    url(r'^auth/logout/$', LogoutUserAPIView.as_view(), name='auth_user_logout'),
    url(r'^profile/$', ProfileAPIView.as_view(), name='user_profile')
]

employees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from .views import (    	
    EmployeeDashboardView,
    
    EmployeeProfileView,
    EmployeeProfileUpdate, #for basic data
    EmployeeProfilePicUpdateView, #for only the profile picture
    EmployeeRiskReportListView, #El empleado solo debe ver los reportes hechos por el mismo
    EmployeeRiskReportListWithSearchView,
    EmployeeRiskReportDetailView,
    EmployeeCreateRiskReportView,
    EmployeeIncidentAccidentListView,
    EmployeeIncidentAccidentListWithSearchView,
    EmployeeIncidentAccidentDetailView,
    EmployeeCreateIncidentAccidentView,
    EmployeeTaskListView,
    EmployeeUpdateTaskStatusView,
)

app_name = 'employees'

urlpatterns = [    
    path('employee/dashboard/', EmployeeDashboardView.as_view(), name='dashboard'),
    path('employee/dashboard/profile/', EmployeeProfileView.as_view(), name='profile'),
    path('employee/dashboard/profile_update/', EmployeeProfileUpdate.as_view(), name='update-profile'),
    path('employee/dashboard/profile_pic_update/', EmployeeProfilePicUpdateView.as_view(), name='update-profile-pic'),
    path('employee/dashboard/risk-report-list/', EmployeeRiskReportListView.as_view(), name='risk-report-list'),
    path('employee/dashboard/risk-report-search/', EmployeeRiskReportListWithSearchView.as_view(), name='risk-report-search'),    
    path('employee/dashboard/risk-report-detial/<int:id>/', EmployeeRiskReportDetailView.as_view(), name='risk-report-detail'),
    path('employee/dashboard/risk-report-create/', EmployeeCreateRiskReportView.as_view(), name='risk-report-create'),    
    path('employee/dashboard/incident-accident-list/', EmployeeIncidentAccidentListView.as_view(), name='incident-accident-list'),
    path('employee/dashboard/incident-accident-search/', EmployeeIncidentAccidentListWithSearchView.as_view(), name='incident-accident-search'),    
    path('employee/dashboard/incident-accident-detial/<int:id>/', EmployeeIncidentAccidentDetailView.as_view(), name='incident-accident-detail'),
    path('employee/dashboard/incident-accident-create/', EmployeeCreateIncidentAccidentView.as_view(), name='incident-accident-create'),
    #task, defenses views
    path('employee/dashboard/task-list/', EmployeeTaskListView.as_view(), name='task-list'),
    path('employee/dashboard/task-status-update/<int:id>/', EmployeeUpdateTaskStatusView.as_view(), name='task-update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.db.models.signals import post_save

from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

from django.utils.translation import ugettext_lazy as _

from django.dispatch import receiver

#USERMANAGER esto para usar el correo electronico como identificador de usuario
class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)        
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

#Clase basica para tener varios tipos de usuarios
class User(AbstractBaseUser, PermissionsMixin):
    email           = models.EmailField(unique=True, blank=False)
    #flags que determinan el rol del usuario
    is_sms_manager	= models.BooleanField(default=False)
    is_employee	= models.BooleanField(default=False)
    #flag staff
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_('Do you think you can be a Superuser?'),
    )
    #flag staff
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    #falg activo
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )    
    
    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

#Clase para los gerentes SMS
class SmsManager(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    #ci          = models.IntegerField(unique=True)
    career      = models.CharField(max_length=50, default='')     
    phone       = models.PositiveBigIntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='sms_managers/profile_pics/', default='sms_managers/profile_pics/default_user_profile_pic.png')    

TYPE_OF_COMPANY = (
    ('1', 'Airport'),#Aeropuerto
    ('2', 'Aeroline'),#Personas Juridicas
    ('3', 'ciac'),#centro de instrucción
    ('4', 'omac'),#Taller OMAC    
)

class Company(models.Model):
    #todo compañia debe tener un gerente sms
    #tambien muchas compañias pueden tener un mismo gerete sms
    company_sms_manager = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='managed_by')
    name                = models.CharField(max_length=100)
    type_of_company     = models.CharField(max_length=1, choices=TYPE_OF_COMPANY, blank=True)
    #rav_type           = models.CharField(max_length=1, choices=TYPE_OF_RAP, blank=True)
    #una compañia puede tener mas de rav
    #hay regulaciones por otros paises rap (peru), far(estados unidos), etc
    #rav_number         = models.IntegerField(null=False, default=0)
    phone               = models.PositiveBigIntegerField(null=False, default=0)
    company_logo        = models.ImageField(upload_to='companys/company_logos/', default='companys/company_logos/default_company_logo.png')
    rif                 = models.PositiveBigIntegerField(null=False, default=0)
    company_mail        = models.EmailField(blank=False, default='mail@mail.com')

class Employee(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    #muchos empleados pertenecen a una compañia
    company     = models.ForeignKey(Company, on_delete=models.CASCADE, related_name = 'employee_of_company', default = False)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    phone       = models.PositiveBigIntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='employees/profile_pics/', default='employees/profile_pics/default_user_profile_pic.png')    

TYPE_OF_RISK = (
    ('1', 'Relacionado con vuelo'),
    ('2', 'E.P.P. (Equipos de protección personal)'),
    ('3', 'Procedimientos'),
    ('4', 'Mantenimiento Aeronáutico'),
    ('5', 'FOD (Objetos extraños)'),
    ('6', 'Orden y limpieza'),
    ('7', 'Acto inseguro'),
    ('8', 'Otros'),
)

LEVEL_OF_RISK = (
    ('1', 'Aceptable'),
    ('2', 'Moderado'),
    ('3', 'Alto'),
    ('4', 'Extremo')    
)

PROBABILITY = (
    ('1', 'Improbable'),
    ('2', 'Remoto'),
    ('3', 'Ocasional'),    
    ('4', 'Frecuente'),
    ('5', 'Probable'),
)

CONSEQUENCE = (
    ('1', 'Insignificante'),
    ('2', 'Menor'),
    ('3', 'Moderado'),    
    ('4', 'Grave'),
    ('5', 'Catastrofico'), 
)


class RiskReport(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='reports_of_company')
    create_at_date  = models.DateTimeField(auto_now_add=True)    
    date            = models.DateField()
    place           = models.CharField(max_length=100)
    type_of_risk    = models.CharField(max_length=1, choices=TYPE_OF_RISK, blank=True)
    photo1          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo2          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo3          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo4          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo5          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    description     = models.TextField(blank=True)
    recmendations   = models.TextField(blank=True, default='')
    is_open         = models.BooleanField(default=True)
    level_of_risk   = models.CharField(max_length=1, choices=LEVEL_OF_RISK, blank=True)
    probability     = models.CharField(max_length=1, choices=PROBABILITY, blank=True)
    consequence     = models.CharField(max_length=1, choices=PROBABILITY, blank=True)            
    level           = models.IntegerField(null=False, default=0)
     
INCIDENT_OR_ACCIDENT = (
    ('1', 'Incidente'),
    ('2', 'Accidente'),
)

class IncidentAccident(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='incident_accident_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='incident_accident_of_company')
    create_at_date  = models.DateTimeField(auto_now_add=True)
    only_incident   = models.CharField(max_length=1, choices=INCIDENT_OR_ACCIDENT, default='1')
    date            = models.DateField()
    place           = models.CharField(max_length=100)    
    photo1          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo2          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo3          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo4          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo5          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    description     = models.TextField(blank=True)

class Task(models.Model):    
    assigned_date   = models.DateTimeField(auto_now_add=True)    
    report          = models.ForeignKey(RiskReport, on_delete=models.CASCADE, related_name='task_of_report')
    reponsable      = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task_of_user')
    manager         = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='task_of_manager', null=True)
    employee        = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='task_of_employee', null=True)
    taskDescription = models.TextField(blank=False)
    completedTask   = models.BooleanField(default=False)
    completed_date  = models.DateTimeField(blank=True, null=True)    

employees/forms.py
from django import forms
from users.models import SmsManager, RiskReport, Employee, IncidentAccident

class EmployeeProfileFormModal(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['name', 'last_name', 'phone']

class EmployeePicFormModal(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['photo',]


class EmployeeRiskReportForm(forms.ModelForm):

    class Meta:
        model = RiskReport
        fields = ['date', 'place', 'type_of_risk', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description', 'recmendations',]  
        """widgets = {
          'description': forms.Textarea(attrs={'rows':20, 'cols':15}),
        }"""

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(EmployeeRiskReportForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })
        self.fields['recmendations'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

class EmployeeIncidentAccidentForm(forms.ModelForm):

    class Meta:
        model = IncidentAccident
        fields = ['date', 'only_incident','place', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description',]        

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(EmployeeIncidentAccidentForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

employees/templates/employee/incidents_and_accidents/datePlaceType.html
    {{ object.date }} <br>
    {{ object.place }} <br>        
    {% if object.type_of_risk == '1' %}
        Relacionado con vuelo<br>
    {% endif %}
    {% if object.type_of_risk == '2' %}
        E.P.P.<br>
    {% endif %}
    {% if object.type_of_risk == '3' %}
        Procedimientos<br>
    {% endif %}
    {% if object.type_of_risk == '4' %}
        Mantenimiento Aeronáutico<br>
    {% endif %}
    {% if object.type_of_risk == '5' %}
        FOD<br>
    {% endif %}
    {% if object.type_of_risk == '6' %}
        Orden y limpieza<br>
    {% endif %}
    {% if object.type_of_risk == '7' %}
        Acto inseguro<br>
    {% endif %}
    {% if object.type_of_risk == '8' %}
        Otros<br>
    {% endif %}               

employees/templates/employee/incidents_and_accidents/employeeIncidentAccidentCreate.html
{% extends '../employeeDashboard.html' %}
{% load static %}
{% block dashboard %}

{% include './incidentAccidentHeader.html' %}

<div class="col m2 hide-on-med-and-down">

</div>

<div class="col s12 m8 center-by-margin card horizontal">
    <form method="post" enctype="multipart/form-data" class="col s12 m9 center-by-margin">
        {% csrf_token %}
        
        <div class="row">
            <div class="input-field col s12">    
                <input type="text" name="date" required="" id="id_date" class="datepicker">
                <label for="id_date">Selecciona una fecha</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                {{ form.only_incident }}
                <label>Tipo de evento:</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s12">    
                {{ form.place }}
                <label for="id_place">Lugar:</label>
            </div>
        </div>
        
        <div class="row">
            <div class="col s12">        
                <label>Opcionalmente puede agregar hasta 5 fotos asociadas al incidente o accidente</label>
            </div>
        </div>
        
        <div class="file-field input-field">
            <div class="btn">
                <span>Foto 1:</span>
                <input type="file" name="photo1" accept="image/*" id="id_photo1">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
        
        <div class="file-field input-field">
            <div class="btn">
                <span>Foto 2:</span>
                <input type="file" name="photo2" accept="image/*" id="id_photo2">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
        
        <div class="file-field input-field">
            <div class="btn">
                <span>Foto 3:</span>
                <input type="file" name="photo3" accept="image/*" id="id_photo3">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
        
        <div class="file-field input-field">
            <div class="btn">
                <span>Foto 4:</span>
                <input type="file" name="photo4" accept="image/*" id="id_photo4">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
        
        <div class="file-field input-field">
            <div class="btn">
                <span>Foto 5:</span>
                <input type="file" name="photo5" accept="image/*" id="id_photo5">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s12">
                {{ form.description }}
                <label for="id_description">Descripción:</label>
            </div>
        </div>
        
        <div class="row center">
            <button type='submit' class="waves-effect waves-light btn-large white-text">
                Crear Reporte Incidente / Accidente
            </button>
        </div>
    </form>
    </div>        
</div>

<div class="col m2 hide-on-med-and-down">

</div>


<!--SCRIPTS-->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $('select').formSelect();
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            i18n: {
                months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
                monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic"],
                weekdays: ["Domingo","Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
                weekdaysShort: ["Dom","Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
                weekdaysAbbrev: ["D","L", "M", "M", "J", "V", "S"],
                today: 'Hoy',
		        clear: 'Limpiar',
		        close: 'Ok',
                cancel: 'Cancelar',
		        labelMonthNext: 'Siguiente mes',
			    labelMonthPrev: 'Mes anterior',			    
            }
        });                
    });        
</script>

<div class="row">
<div class="col s2"></div>
<div class="col s8">

</div>

{% endblock %}

employees/templates/employee/incidents_and_accidents/employeeIncidentAccidentDetail.html
{% extends '../employeeDashboard.html' %}
{% load static %}
{% block dashboard %}

{% include './incidentAccidentHeader.html' %}

<div class="col m2 hide-on-med-and-down">

</div>

<div class="col s12 m8 center-by-margin">
    <div class="card">
        <div class="card-image">
            <div class="carousel carousel-slider center">        
                <div class="carousel-item white-text" href="#one!" style="background-size: contain; background-position: center center; background-repeat: no-repeat; background-image: url({{ object.photo1.url }})">
                  <div class="indicators" style="position: relative;">
                    {% include './datePlaceType.html' %}
                  </div>
                </div>
                <div class="carousel-item white-text" href="#two!" style="background-size: contain; background-position: center center; background-repeat: no-repeat; background-image: url({{ object.photo2.url }})">
                    <div class="indicators" style="position: relative;">
                        {% include './datePlaceType.html' %}
                    </div>
                </div>
                <div class="carousel-item white-text" href="#three!" style="background-size: contain; background-position: center center; background-repeat: no-repeat; background-image: url({{ object.photo3.url }})">
                    <div class="indicators" style="position: relative;">
                        {% include './datePlaceType.html' %}
                    </div>
                </div>
                <div class="carousel-item white-text" href="#four!" style="background-size: contain; background-position: center center; background-repeat: no-repeat; background-image: url({{ object.photo4.url }})">
                    <div class="indicators" style="position: relative;">
                        {% include './datePlaceType.html' %}
                    </div>
                </div>
                <div class="carousel-item white-text" href="#four!" style="background-size: contain; background-position: center center; background-repeat: no-repeat; background-image: url({{ object.photo5.url }})">
                    <div class="indicators" style="position: relative;">
                        {% include './datePlaceType.html' %}
                    </div>
                  </div>
            </div>
        </div>
        <div class="card-content">           
            <h5>Decripción:</h5>
            <p>{{ object.description }}</p><br>            
        </div>        
    </div>

</div>

<div class="col m2 hide-on-med-and-down">

</div>

{% endblock %}

employees/templates/employee/incidents_and_accidents/employeeIncidentAccidentList.html
{% extends '../employeeDashboard.html' %}
{% load static %}
{% block dashboard %}

{% include './incidentAccidentHeader.html' %}

<div class="col m2 hide-on-med-and-down">

</div>

<div class="col s12 m8 center-by-margin main-content-center">
    <div class="row tab-container">
        <div class = "col s12 tab-container-tabs">
            <ul class = "tabs">
                <li class = "tab col s6"><a class = "active" href = "#inbox">Incidentes</a></li>
                <li class = "tab col s6"><a href = "#unread">Accidentes</a></li>            
            </ul>
        </div>

        <div id = "inbox" class = "col s12">
            <ul class="collection with-header mb-mobile-for-floating-btn">
                <li class="collection-header">
                    <form action='{% url 'employees:incident-accident-search' %}' method='GET'>
                        {% csrf_token %}
                        <div class="input-field">
                            <i class="material-icons prefix">search</i>        
                            <input name="my_search" type="text" placeholder="Busqueda por descripcíon, fecha o quien hizo el reporte">
                        </div>
                    </form>
                </li>        
                {% for instance in incidents.all %}
                <li class="collection-item avatar">
                <img src="{{ instance.photo1.url }}" alt="Image Not Found" class="" style="max-width: 3rem; position: absolute; left: 1rem;">
                <span class="title">{{ instance.date }}</span>
                <p class="colecction-elipsis-text">
                    {{ instance.place }} <br>                
                    {{ instance.description }}<br>
                </p>
                <a href="{% url 'employees:incident-accident-detail' instance.id %}" class="secondary-content"><i class="material-icons">remove_red_eye</i></a>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div id = "unread" class = "col s12">
            <ul class="collection with-header mb-mobile-for-floating-btn">
                <li class="collection-header">
                    <form action='{% url 'employees:incident-accident-search' %}' method='GET'>
                        {% csrf_token %}
                        <div class="input-field">
                            <i class="material-icons prefix">search</i>        
                            <input name="my_search" type="text" placeholder="Busqueda por descripcíon, fecha o quien hizo el reporte">
                        </div>
                    </form>
                </li>        
                {% for instance in accidents.all %}
                <li class="collection-item avatar">
                <img src="{{ instance.photo1.url }}" alt="Image Not Found" class="" style="max-width: 3rem; position: absolute; left: 1rem;">
                <span class="title">{{ instance.date }}</span>
                <p class="colecction-elipsis-text">
                    {{ instance.place }} <br>                
                    {{ instance.description }}<br>
                </p>
                <a href="{% url 'employees:incident-accident-detail' instance.id %}" class="secondary-content"><i class="material-icons">remove_red_eye</i></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!--Floating Button-->
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light red tooltipped" data-position="top" data-tooltip="Nuevo Incidente / Accidente" href="{% url 'employees:incident-accident-create' %}">
            <i class="material-icons">add</i>
        </a>
    </div>
</div>

<div class="col m2 hide-on-med-and-down">

</div>

{% if messages %}  
    {% for message in messages %}
        <script>
            document.addEventListener('DOMContentLoaded', function toast() {
                let message = "{{ message }}"
                var toastHTML = '<span>'+message+'</span>';
                M.toast({html: toastHTML, displayLength: 5000,classes: 'rounded'});
                
            });            
        </script>
    {% endfor %} 
{% endif %}

{% endblock %}

employees/templates/employee/incidents_and_accidents/incidentAccidentHeader.html
<div class="row risk-report-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2 mt-1">Incidentes / Accidentes </h3>
        </div>       
    </div>
</div>